name: Python Unit Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change if you use a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-dev.txt
          pip install pandas openpyxl

      - name: Run unit tests only
        run: |
          cd backend
          pytest tests/unit/ --maxfail=3 --disable-warnings -v